global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Allow Tempo to write metrics
remote_write:
  - url: http://tempo:3200/prometheus/api/v1/write

scrape_configs:
  # Scrape OTEL Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '.*grpc_io.*'
        action: drop

  # Scrape Tempo metrics
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']