/// <reference types="vitest/config" />
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vitest/config';
import { viteStaticCopy } from 'vite-plugin-static-copy';

export default defineConfig({
  define: {
    __APP_VERSION__: JSON.stringify(process.env.VITE_APP_VERSION || 'dev'),
    __ENABLE_DEV_FEATURES__: process.env.NODE_ENV === 'development',
    // vite only exposes VITE_-prefixed vars on import.meta.env; the config
    // loader branches on APP_CONFIG, so bake it in explicitly
    'import.meta.env.APP_CONFIG': JSON.stringify(process.env.APP_CONFIG || '')
  },
  plugins: [
    sveltekit(),
    viteStaticCopy({
      targets: [
        {
          src: `src/config/static/${process.env.APP_CONFIG || process.env.NODE_ENV || 'development'}/index.json`,
          dest: '',
          rename: 'config.json'
        }
      ]
    })
  ],
  // Under vitest the modules are loaded through vite's SSR pipeline, which would
  // otherwise pick svelte's server export and render components to a string
  // instead of mounting them into jsdom. The browser condition is what makes
  // `render()` from @testing-library/svelte produce real DOM. Scoped to VITEST
  // so `vite build`, `vite dev` and SSR are untouched.
  resolve: process.env.VITEST ? { conditions: ['browser'] } : undefined,
  build: {
    // explicit target so the worker build isn't forced below es2020 in CI
    // (esbuild can't downlevel some deps' destructuring, which broke the
    // worker build); es2020 is a safe, widely-supported floor
    target: 'es2020',
    chunkSizeWarningLimit: 1000,
    sourcemap: false,
    minify: 'terser',
    terserOptions: {
      compress: {
        // keep console.error/console.warn: they are the only production
        // logging the k8s pods and workers emit
        pure_funcs: process.env.NODE_ENV === 'production'
          ? ['console.log', 'console.debug', 'console.info']
          : [],
        drop_debugger: true
      }
    }
  },
  ssr: {
    noExternal: ['@tanstack/svelte-query', '@tanstack/query-core']
  },
  optimizeDeps: {
    include: ['date-fns', 'graphql-request'],
    // Packages that ship .svelte files can't be esbuild-prebundled (no .svelte
    // loader in the dep optimizer) — exclude so the svelte plugin handles them.
    // Otherwise `vite dev` crashes on startup.
    exclude: ['@fortawesome/fontawesome-svg-core', '@tanstack/svelte-query', 'svelte-fa', 'svelte-sonner']
  },
  test: {
    // jsdom for everything: the pure-logic suites do not care, and it is what
    // lets a component test and a logic test live side by side in the same
    // component folder without a per-file environment pragma.
    environment: 'jsdom',
    // Unit tests only. Playwright owns tests/e2e — vitest must never claim a
    // `.spec.ts` from there, or `yarn test` would try to run the browser suite.
    include: ['src/**/*.{test,spec}.{js,ts}'],
    exclude: ['**/node_modules/**', 'tests/e2e/**', 'build/**', '.svelte-kit/**'],
    setupFiles: ['./vitest-setup.ts'],
    // Tests import from `vitest` explicitly; no globals are injected, so
    // svelte-check sees the same symbols the runtime does.
    globals: false,
    restoreMocks: false,
    coverage: {
      provider: 'v8',
      // text for the terminal, html to browse locally, lcov for external tools.
      // json-summary and json are what the CI reporter reads: the summary gives
      // it the totals table, the full json lets it name which files a pull
      // request actually changed the coverage of.
      reporter: ['text', 'html', 'lcov', 'json-summary', 'json'],
      reportsDirectory: './coverage',
      include: ['src/**/*.{ts,js,svelte}'],
      // What is measured is what ships. Everything below exists only to
      // support Storybook or the test suite -- the demo wrappers and fixtures
      // under `__stories__/` (AuthCardDemo, GlobalToasterDemo, StoryContainer,
      // the `offline/` stubs, show-fixtures, profileFixtures, auth-stubs) and
      // the helpers under `__tests__/`. None of it is reachable from the app,
      // all of it sat at 0%, and counting it inflated the denominator with
      // code the gate is not about. `*.stories.*` rather than `*.stories.ts`
      // so a `.stories.svelte` would be caught too.
      exclude: [
        'src/**/*.test.ts',
        'src/**/*.spec.ts',
        '**/*.stories.*',
        '**/__stories__/**',
        '**/__tests__/**',
        '**/__fixtures__/**',
        'src/gql/**', // generated by graphql-codegen
        'src/**/*.d.ts',
        // Route views are e2e's territory, by an explicit decision: a
        // +page.svelte is a composition of already-tested components plus a
        // loader, and what is worth asserting about it is that the page works
        // end to end -- which tests/e2e does. Measuring it here would drag the
        // number down with markup nobody intends to unit-test, and reaching
        // 80% on it would mean shallow mount-and-see tests duplicating
        // Playwright. Route LOGIC is NOT excluded: the .bloc.svelte.ts and
        // .logic.ts beside each route stay measured, and sit at ~94%.
        'src/routes/**/*.svelte'
      ],
      /*
        The gate: 80% everywhere, and the run fails below it.

        This is one number rather than a per-directory table on purpose. A
        threshold people have to look up is a threshold that drifts; "unit
        tests do not pass under 80%" is a rule anyone can hold in their head.

        What it measures is the code unit tests are responsible for. Route
        views are excluded above and covered by e2e; everything else -- the
        components, their blocs, the route logic, the services, the stores, the
        server hooks, the workers, the utils -- is in.

        All four metrics sit at 80. Branches and functions run structurally
        lower than statements in Svelte (every `{#if}`, `??` and handler is its
        own branch or function), so they are the ones that will bite first; at
        the time of writing they are at 85.5% and 87.7%, so there is real
        headroom rather than a number tuned to just scrape past.
      */
      thresholds: {
        statements: 80,
        branches: 80,
        functions: 80,
        lines: 80
      }
    }
  }
});
