/// <reference types="vitest/config" />
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vitest/config';
import { viteStaticCopy } from 'vite-plugin-static-copy';

export default defineConfig({
  define: {
    __APP_VERSION__: JSON.stringify(process.env.VITE_APP_VERSION || 'dev'),
    __ENABLE_DEV_FEATURES__: process.env.NODE_ENV === 'development',
    // vite only exposes VITE_-prefixed vars on import.meta.env; the config
    // loader branches on APP_CONFIG, so bake it in explicitly
    'import.meta.env.APP_CONFIG': JSON.stringify(process.env.APP_CONFIG || '')
  },
  plugins: [
    sveltekit(),
    viteStaticCopy({
      targets: [
        {
          src: `src/config/static/${process.env.APP_CONFIG || process.env.NODE_ENV || 'development'}/index.json`,
          dest: '',
          rename: 'config.json'
        }
      ]
    })
  ],
  // Under vitest the modules are loaded through vite's SSR pipeline, which would
  // otherwise pick svelte's server export and render components to a string
  // instead of mounting them into jsdom. The browser condition is what makes
  // `render()` from @testing-library/svelte produce real DOM. Scoped to VITEST
  // so `vite build`, `vite dev` and SSR are untouched.
  resolve: process.env.VITEST ? { conditions: ['browser'] } : undefined,
  build: {
    // explicit target so the worker build isn't forced below es2020 in CI
    // (esbuild can't downlevel some deps' destructuring, which broke the
    // worker build); es2020 is a safe, widely-supported floor
    target: 'es2020',
    chunkSizeWarningLimit: 1000,
    sourcemap: false,
    minify: 'terser',
    terserOptions: {
      compress: {
        // keep console.error/console.warn: they are the only production
        // logging the k8s pods and workers emit
        pure_funcs: process.env.NODE_ENV === 'production'
          ? ['console.log', 'console.debug', 'console.info']
          : [],
        drop_debugger: true
      }
    }
  },
  ssr: {
    noExternal: ['@tanstack/svelte-query', '@tanstack/query-core']
  },
  optimizeDeps: {
    include: ['date-fns', 'graphql-request'],
    // Packages that ship .svelte files can't be esbuild-prebundled (no .svelte
    // loader in the dep optimizer) — exclude so the svelte plugin handles them.
    // Otherwise `vite dev` crashes on startup.
    exclude: ['@fortawesome/fontawesome-svg-core', '@tanstack/svelte-query', 'svelte-fa', 'svelte-sonner']
  },
  test: {
    // jsdom for everything: the pure-logic suites do not care, and it is what
    // lets a component test and a logic test live side by side in the same
    // component folder without a per-file environment pragma.
    environment: 'jsdom',
    // Unit tests only. Playwright owns tests/e2e — vitest must never claim a
    // `.spec.ts` from there, or `yarn test` would try to run the browser suite.
    include: ['src/**/*.{test,spec}.{js,ts}'],
    exclude: ['**/node_modules/**', 'tests/e2e/**', 'build/**', '.svelte-kit/**'],
    setupFiles: ['./vitest-setup.ts'],
    // Tests import from `vitest` explicitly; no globals are injected, so
    // svelte-check sees the same symbols the runtime does.
    globals: false,
    restoreMocks: false,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html', 'lcov'],
      reportsDirectory: './coverage',
      include: ['src/**/*.{ts,js,svelte}'],
      exclude: [
        'src/**/*.test.ts',
        'src/**/*.spec.ts',
        'src/**/*.stories.ts',
        'src/**/__fixtures__/**',
        'src/**/__tests__/**',
        'src/gql/**', // generated by graphql-codegen
        'src/**/*.d.ts'
      ]
      // The eventual gate is 80% across the board. It stays off until the
      // component suites exist — turning it on now would fail every run, since
      // components are close to uncovered. Uncomment and raise to 80 once the
      // suites land.
      // thresholds: {
      //   statements: 80,
      //   branches: 80,
      //   functions: 80,
      //   lines: 80
      // }
    }
  }
});
