name: "Test Status Check"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/test.yml
    
  e2e-tests:
    name: E2E Tests
    uses: ./.github/workflows/e2e-tests.yml
    
  all-tests-pass:
    name: All Tests Pass
    runs-on: ubuntu-latest
    needs: [unit-tests, e2e-tests]
    steps:
      - name: Tests Summary
        run: |
          echo "✅ All tests passed successfully!"
          echo "Unit Tests: ✅"
          echo "E2E Tests: ✅"